apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gh-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:      
      number: 80      
      name: http      
      protocol: HTTP    
    hosts:
    - 87.106.162.134
