apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fosps-domain-cert
  namespace: istio-system
spec:
  secretName: fosps-domain-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "fosps.gravitatehealth.eu"
  issuerRef:
    name: letsencrypt-cert
    kind: ClusterIssuer
    group: cert-manager.io