apiVersion: install.istio.io/v1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: prod-operator
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      #k8s:
      #  overlays:
      #  - apiVersion: apps/v1
      #    kind: Deployment
      #    name: istio-ingressgateway
      #    patches:
      #    - path: kind
      #      value: DaemonSet
      #    - path: spec.strategy
      #    - path: spec.updateStrategy
      #      value:
      #        rollingUpdate:
      #          maxUnavailable: 50%
      #        type: RollingUpdate
    egressGateways:
    - name: istio-egressgateway
      enabled: true
